version: 2

project_name: flakehawk

builds:
  - id: flakehawk
    main: ./cmd/flakehawk
    binary: flakehawk
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    name_template: "flakehawk_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: hunterkritik-byte
    name: FlakeHawk
